package exceptionsHandling;

public class TryCatch {

	public static void main(String[] args) {
//		throw new ArithmeticException("/ by Zero");
//		System.out.println("statement 1");
//		try {
			System.out.println(10 / 0);
//		} catch (Exception e) {
//			System.out.println("-----printStackTrace()-----");
//			e.printStackTrace();
//			System.out.println("-----toString-----");
//			System.out.println(e.toString());
//			System.out.println("-----print e-----");
//			System.out.println(e);
//			System.out.println("-----getMessage-----");
//			System.out.println(e.getMessage());
//			System.out.println("-----getStackTrace-----");
//			System.out.println(e.getStackTrace());
//		}
//		System.out.println("statement 3");
	}
}
